#include <QtTest/QtTest>

#include "airborne_runtime.h"
#include "h_problem_mission_runtime.h"
#include "mission_runtime_factory.h"

#include "competition_core/protocol/command_handler.h"
#include "h_problem_core/mission/mission_plan_store.h"
#include "h_problem_core/protocol/envelope_builder.h"

#include <QFile>
#include <QTemporaryDir>

class AirborneRuntimeTests : public QObject {
    Q_OBJECT

private slots:
    void selectsStoredMissionPlanOverAutogeneratedPlan();
    void loadsGenericTaskPlanBeforeLegacyMissionPlan();
    void callbackPublisherPublishesGenericEventsAndSummaries();
    void hProblemRuntimePublishesGenericEventsAndSummary();
    void hProblemRuntimeStopsWhenStateRequestsStop();
    void missionRuntimeFactoryCreatesDefaultHProblemRuntime();
    void missionRuntimeFactoryRejectsUnknownTask();
    void commandHandlerHandlesControlCommandBytes();
};

void AirborneRuntimeTests::selectsStoredMissionPlanOverAutogeneratedPlan() {
    hcore::CaseConfig config;
    config.case_id = "plan-test";
    config.start_cell = "A1B1";
    config.tick_interval_ms = 10;

    hcore::MissionPlan stored_plan;
    stored_plan.case_id = "plan-test";
    stored_plan.start_cell = "A1B1";
    stored_plan.route = {"A1B1", "A2B1"};
    stored_plan.terminal_cell = "A2B1";

    QString error;
    const hcore::MissionPlan selected = airborne::selectMissionPlan(config, stored_plan, &error);
    QVERIFY2(error.isEmpty(), qPrintable(error));
    QCOMPARE(selected.route, stored_plan.route);
}

void AirborneRuntimeTests::loadsGenericTaskPlanBeforeLegacyMissionPlan() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString path = dir.filePath("active_mission_plan.json");

    hcore::MissionPlan mission_plan;
    mission_plan.case_id = "task-plan-test";
    mission_plan.start_cell = "A1B1";
    mission_plan.no_fly_cells = {"A3B3"};
    mission_plan.route = {"A1B1", "A2B1", "A2B2"};
    mission_plan.terminal_cell = "A2B2";
    mission_plan.landing_enabled = true;
    mission_plan.descent_angle_deg = 30.0;
    mission_plan.takeoff_anchor_x_cm = 10.0;
    mission_plan.takeoff_anchor_y_cm = 20.0;

    const competition::TaskPlan task_plan = hcore::taskPlanFromMissionPlan(mission_plan);

    QString error;
    QVERIFY2(hcore::storeTaskPlan(task_plan, path, &error), qPrintable(error));
    const auto loaded = airborne::loadOptionalMissionPlan(path, &error);

    QVERIFY2(error.isEmpty(), qPrintable(error));
    QVERIFY(loaded.has_value());
    QCOMPARE(loaded->case_id, mission_plan.case_id);
    QCOMPARE(loaded->route, mission_plan.route);
    QCOMPARE(loaded->terminal_cell, mission_plan.terminal_cell);
    QCOMPARE(loaded->landing_enabled, mission_plan.landing_enabled);
    QCOMPARE(loaded->descent_angle_deg.value(), mission_plan.descent_angle_deg.value());
}

void AirborneRuntimeTests::callbackPublisherPublishesGenericEventsAndSummaries() {
    QVector<competition::TaskEvent> events;
    QVector<competition::TaskSummary> summaries;
    QVector<quint64> event_sequences;
    QVector<quint64> summary_sequences;

    airborne::CallbackEventPublisher publisher(
        [&](quint64 sequence, const competition::TaskEvent &event) {
            event_sequences.append(sequence);
            events.append(event);
            return true;
        },
        [&](quint64 sequence, const competition::TaskSummary &summary) {
            summary_sequences.append(sequence);
            summaries.append(summary);
            return true;
        });

    competition::TaskEvent event;
    event.task_id = "demo";
    event.event_type = "telemetry";
    QVERIFY(publisher.publishEvent(7, event));

    competition::TaskSummary summary;
    summary.task_id = "demo";
    summary.task_type = "h_problem";
    QVERIFY(publisher.publishSummary(8, summary));

    QCOMPARE(events.size(), 1);
    QCOMPARE(events.first().event_type, QString("telemetry"));
    QCOMPARE(event_sequences.first(), static_cast<quint64>(7));
    QCOMPARE(summaries.size(), 1);
    QCOMPARE(summaries.first().task_type, QString("h_problem"));
    QCOMPARE(summary_sequences.first(), static_cast<quint64>(8));
}

void AirborneRuntimeTests::hProblemRuntimePublishesGenericEventsAndSummary() {
    hcore::CaseConfig config;
    config.case_id = "runtime-test";
    config.start_cell = "A1B1";
    config.tick_interval_ms = 10;
    config.animals.append({"A2B1", "rabbit", 3});

    hcore::MissionPlan plan;
    plan.case_id = "runtime-test";
    plan.start_cell = "A1B1";
    plan.route = {"A1B1", "A2B1"};
    plan.terminal_cell = "A2B1";

    QVector<competition::TaskEvent> events;
    QVector<competition::TaskSummary> summaries;
    QVector<quint64> event_sequences;
    QVector<quint64> summary_sequences;
    airborne::CallbackEventPublisher publisher(
        [&](quint64 sequence, const competition::TaskEvent &event) {
            event_sequences.append(sequence);
            events.append(event);
            return true;
        },
        [&](quint64 sequence, const competition::TaskSummary &summary) {
            summary_sequences.append(sequence);
            summaries.append(summary);
            return true;
        });

    competition::CommandState state;
    airborne::HProblemMissionRuntime runtime(config, plan, &publisher);

    QCOMPARE(runtime.execute(state, 0.0), 0);
    QCOMPARE(events.size(), 3);
    QCOMPARE(events.at(0).task_id, QString("runtime-test"));
    QCOMPARE(events.at(0).event_type, QString("telemetry"));
    QCOMPARE(events.at(0).sequence_index, static_cast<quint32>(0));
    QCOMPARE(events.at(0).waypoint_id, QString("A1B1"));
    QCOMPARE(events.at(1).event_type, QString("telemetry"));
    QCOMPARE(events.at(1).waypoint_id, QString("A2B1"));
    QCOMPARE(events.at(2).event_type, QString("detection"));
    QCOMPARE(events.at(2).waypoint_id, QString("A2B1"));
    QVERIFY(events.at(2).payload_json.contains("\"animal_name\":\"rabbit\""));
    QCOMPARE(event_sequences, QVector<quint64>({1, 2, 3}));

    QCOMPARE(summaries.size(), 1);
    QCOMPARE(summaries.first().task_id, QString("runtime-test"));
    QCOMPARE(summaries.first().task_type, QString("h_problem"));
    QCOMPARE(summaries.first().visited_waypoints, static_cast<quint32>(2));
    QVERIFY(summaries.first().payload_json.contains("\"rabbit\":3"));
    QCOMPARE(summary_sequences.first(), static_cast<quint64>(4));
}

void AirborneRuntimeTests::hProblemRuntimeStopsWhenStateRequestsStop() {
    hcore::CaseConfig config;
    config.case_id = "stop-test";
    config.start_cell = "A1B1";
    config.tick_interval_ms = 10;

    hcore::MissionPlan plan;
    plan.case_id = "stop-test";
    plan.start_cell = "A1B1";
    plan.route = {"A1B1", "A2B1", "A3B1"};
    plan.terminal_cell = "A3B1";

    competition::CommandState state;
    int published_events = 0;
    int published_summaries = 0;
    quint64 published_sequence = 0;
    airborne::CallbackEventPublisher publisher(
        [&](quint64 sequence, const competition::TaskEvent &) {
            published_sequence = sequence;
            ++published_events;
            state.requestStop();
            return true;
        },
        [&](quint64, const competition::TaskSummary &) {
            ++published_summaries;
            return true;
        });
    airborne::HProblemMissionRuntime runtime(config, plan, &publisher);

    QCOMPARE(runtime.execute(state, 0.0), 0);
    QCOMPARE(published_events, 1);
    QCOMPARE(published_summaries, 0);
    QCOMPARE(published_sequence, static_cast<quint64>(1));
}

void AirborneRuntimeTests::missionRuntimeFactoryCreatesDefaultHProblemRuntime() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString case_path = dir.filePath("factory_case.json");
    QFile case_file(case_path);
    QVERIFY(case_file.open(QIODevice::WriteOnly | QIODevice::Text));
    case_file.write(R"({"case_id":"factory-test","start_cell":"A1B1","tick_interval_ms":1,"animals":[]})");
    case_file.close();

    const QString plan_path = dir.filePath("active_mission_plan.json");
    hcore::MissionPlan plan;
    plan.case_id = "factory-test";
    plan.start_cell = "A1B1";
    plan.route = {"A1B1"};
    plan.terminal_cell = "A1B1";
    QString store_error;
    QVERIFY2(hcore::storeMissionPlan(plan, plan_path, &store_error), qPrintable(store_error));

    int published_summaries = 0;
    airborne::CallbackEventPublisher publisher(
        [](quint64, const competition::TaskEvent &) { return true; },
        [&](quint64, const competition::TaskSummary &) {
            ++published_summaries;
            return true;
        });

    QString error;
    auto runtime = airborne::createMissionRuntime(
        "h_problem",
        case_path,
        plan_path,
        &publisher,
        &error);

    QVERIFY2(error.isEmpty(), qPrintable(error));
    QVERIFY(runtime != nullptr);

    competition::CommandState state;
    QCOMPARE(runtime->execute(state, 0.0), 0);
    QCOMPARE(published_summaries, 1);
}

void AirborneRuntimeTests::missionRuntimeFactoryRejectsUnknownTask() {
    airborne::CallbackEventPublisher publisher(
        [](quint64, const competition::TaskEvent &) { return true; },
        [](quint64, const competition::TaskSummary &) { return true; });

    QString error;
    auto runtime = airborne::createMissionRuntime(
        "missing_problem",
        "unused_case.json",
        "unused_plan.json",
        &publisher,
        &error);

    QVERIFY(runtime == nullptr);
    QVERIFY(error.contains("unknown mission runtime"));
    QVERIFY(error.contains("h_problem"));
}

void AirborneRuntimeTests::commandHandlerHandlesControlCommandBytes() {
    QTemporaryDir dir;
    QVERIFY(dir.isValid());
    const QString output_path = dir.filePath("active_mission_plan.json");

    competition::CommandState state;

    Envelope start;
    start.mutable_control_command()->set_type(COMMAND_TYPE_START_MISSION);
    start.mutable_control_command()->set_task_id("demo");
    std::string start_bytes;
    QVERIFY(start.SerializeToString(&start_bytes));
    competition::AckResult ack = competition::handleCommandBytes(
        QByteArray(start_bytes.data(), static_cast<qsizetype>(start_bytes.size())),
        output_path,
        &state);
    QVERIFY2(ack.success, qPrintable(ack.message));
    QVERIFY(state.isStartRequested());
    QVERIFY(!state.isStopRequested());

    Envelope ping;
    ping.mutable_control_command()->set_type(COMMAND_TYPE_PING);
    ping.mutable_control_command()->set_task_id("demo");
    std::string ping_bytes;
    QVERIFY(ping.SerializeToString(&ping_bytes));
    ack = competition::handleCommandBytes(
        QByteArray(ping_bytes.data(), static_cast<qsizetype>(ping_bytes.size())),
        output_path,
        &state);
    QVERIFY2(ack.success, qPrintable(ack.message));
    QCOMPARE(ack.message, QString("pong"));

    Envelope stop;
    stop.mutable_control_command()->set_type(COMMAND_TYPE_STOP_MISSION);
    stop.mutable_control_command()->set_task_id("demo");
    std::string stop_bytes;
    QVERIFY(stop.SerializeToString(&stop_bytes));
    ack = competition::handleCommandBytes(
        QByteArray(stop_bytes.data(), static_cast<qsizetype>(stop_bytes.size())),
        output_path,
        &state);
    QVERIFY2(ack.success, qPrintable(ack.message));
    QVERIFY(state.isStopRequested());
}

QTEST_MAIN(AirborneRuntimeTests)
#include "test_airborne_runtime.moc"
